### ISSUE TITLE
Learnable tau incompatible with ProDMP

### ISSUE THREAD

**Issue by ScheiklP** [ALRhub/MP_PyTorch#118]
Hi Bruce,
I think I found a problem with the current implementation of  `learn_tau=True` in the ProDMP case.

**Describe the bug**
If you set ``learn_tau=True``, the parameters passed to ``update_inputs`` of the ProDMP will overwrite the ``tau`` value of the phase generator [here](https://github.com/ALRhub/MP_PyTorch/blob/main/mp_pytorch/phase_gn/phase_generator.py#L127).
This invalidates the precomputed values, because they depend on [`scaled_dt`](https://github.com/ALRhub/MP_PyTorch/blob/main/mp_pytorch/basis_gn/prodmp_basis.py#L83), which in turn depends on `tau` and is only set in the [init](https://github.com/ALRhub/MP_PyTorch/blob/main/mp_pytorch/basis_gn/prodmp_basis.py#L40) of the `ProDMPBasisGenerator`.

**Possible solution**
Maybe we could add:
1. recalculate `scaled_dt` in `pre_compute()`
2. check in `update_inputs` if `pre_compute()` should be called.

**Comment by BruceGeLi** [comment]
Hi Paul,

I checked the code and I think the issue suggested by you is not a bug. Everything I am writing here is based my best knowledge:
The pre-computation is applied in the unit free time space.
Tau and delay are two parameters to map between absolute time  and unit-free time (scaled) spaces: scaled_time = (time - delay) / tau
The scaled dt represents the numerical precision in this "unit free time" space to apply the pre-computation.
It was determined at the pre-computation phase, and the value of it was computed by the initial tau and initial absolute dt scaled_dt = dt / tau, but later this precision is not necessarily depending on the new tau anymore. But the precision in absolute time space will change as dt = scaled_dt * tau
The idea overall is that we do the pre-computation in a unit free space, and they use the results in absolute time space by adjusting the mapping relation from unit free time space to absolute time space. Once the precision in unit free time space was defined, we do not change it anymore. Thus you can only find one setter of scaled_dt in prodmp code.
The pre_compute() was only called once when the ProDMP instance is initialized, and will never be called again throughout the rest procedures.

The workflow of using the pre-computed values are:
Map the queried time points in abs time space to unit free time space using the current tau and delay.
Interpolate the values at the mapped queried time points using the pre-computed values and linear-interpolation.
